@echo off
echo Activating virtual environment...
call venv\Scripts\Activate

echo Fetching data...
python -m src.api.data_dragon.data_dragon

echo Generating Release build files...
cmake -B build/release -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles"

echo Building Release...
cmake --build build/release