name: CI Pipeline

on:
  push:
    branches:
      - main
      - "feature/*"
      - "refactor/*"
      - "fix/*"
      - "ci/*"
      - "docs/*"
      - "release/*"
      - "hotfix/*"
  pull_request:
    branches:
      - main
      - "feature/*"
      - "refactor/*"
      - "fix/*"
      - "ci/*"
      - "docs/*"
      - "release/*"
      - "hotfix/*"

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Verify Python Version
        run: python --version

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install -e .

      - name: Validate Commit Messages
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js

      - name: Ensure validate.sh is Executable
        run: chmod +x validate.sh

      - name: Run validate.sh
        run: ./validate.sh
