name: Release Version on Release Branch

on:
  push:
    branches:
      - release/**
      - release

jobs:
  bump_version:
    name: Bump Version & Create PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Commitizen
        run: pip install commitizen

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version and changelog (uncommitted)
        id: cz
        run: |
          cz bump --yes --changelog
        continue-on-error: false

      - name: Create PR to main with version bump
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          branch: ${{ github.ref_name }}
          title: "Release ${{ github.ref_name }} → main"
          body: |
            Auto-created PR to merge the release branch `${{ github.ref_name }}` into `main`
            after version bump and tagging.
          commit-message: "chore(release): bump version"
          add-paths: |
            pyproject.toml
            CHANGELOG.md
          delete-branch: false
          labels: automated

      - name: Push tags (after PR commit)
        run: git push --tags
